### ISSUE TITLE
Char from the right wall dissapears when a 'f' char is spawned near it, or when the snake is turning right at it. 

### ISSUE THREAD

**Issue by ognyanstoimenov** [ogitaki/CSharp-OOP-Project#1]
![image](https://cloud.githubusercontent.com/assets/23344743/21557813/4ee852f8-ce3a-11e6-803d-f49bb87ef7d0.png)

**Comment by marktitorenkov** [comment]
# Fixed
Console.ReadKey(true) - *Determines whether to display the pressed key in the console window. true to not display the pressed key; otherwise, false.*
